version: "3.9"

services:
  lilmokinlil-vite-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lIlmokinlIl-vite-site
    ports:
      - "3002:80"
    restart: unless-stopped
